// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTg7nMT_hL2ipiHJ8JzPuI2RkbxUQovWg',
    appId: '1:822401031550:web:628f90bbd6d88c0fc8e72f',
    messagingSenderId: '822401031550',
    projectId: 'texi-d215f',
    authDomain: 'texi-d215f.firebaseapp.com',
    databaseURL: 'https://texi-d215f-default-rtdb.firebaseio.com',
    storageBucket: 'texi-d215f.firebasestorage.app',
    measurementId: 'G-6YS894J8V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIapegN1VICvHyY0YEZIPIXLdUcfJfj0g',
    appId: '1:822401031550:android:8d9d6a7d089cfe8ac8e72f',
    messagingSenderId: '822401031550',
    projectId: 'texi-d215f',
    databaseURL: 'https://texi-d215f-default-rtdb.firebaseio.com',
    storageBucket: 'texi-d215f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuE-I5BFxqpRH5J-Y0S8-5tf2fT1G35Jg',
    appId: '1:822401031550:ios:0e180e48c33c5b24c8e72f',
    messagingSenderId: '822401031550',
    projectId: 'texi-d215f',
    databaseURL: 'https://texi-d215f-default-rtdb.firebaseio.com',
    storageBucket: 'texi-d215f.firebasestorage.app',
    iosBundleId: 'com.example.appTexiFltrDriver',
  );
}
